const stageMapping = require('./stageMapping');
const stageHighlighting = require('./stageHighlighting');
const stageProgress = require('./stageProgress');
const stageFormatters = require('./stageFormatters');
const cardRenderers = require('./cardRenderers');
const accessShareHelpers = require('./accessShareHelpers');
const telegramSender = require('./telegramSender');

const publicExports = {
  ...cardRenderers,
  ...accessShareHelpers,
  ...telegramSender,
  buildCustomerOrderItemsStatusLines: cardRenderers.buildCustomerOrderItemsStatusLines,
  buildCustomerOrderProgressSummary: cardRenderers.buildCustomerOrderProgressSummary,
  getOrderProgressSnapshot: stageProgress.getOrderProgressSnapshot,
  getItemProgressSnapshot: stageProgress.getItemProgressSnapshot,
  getItemTrackedStageProgress: stageProgress.getItemTrackedStageProgress,
  ORDER_PRIMARY_HEADERS: stageMapping.ORDER_PRIMARY_HEADERS,
  ORDER_COLUMN_KEY_TO_PRIMARY_INDEX: stageMapping.ORDER_COLUMN_KEY_TO_PRIMARY_INDEX,
  PRIMARY_INDEX_TO_ORDER_COLUMN_KEY: stageMapping.PRIMARY_INDEX_TO_ORDER_COLUMN_KEY,
  ORDER_TRACKED_PRIMARY_START_INDEX: stageMapping.ORDER_TRACKED_PRIMARY_START_INDEX,
  ORDER_TRACKED_PRIMARY_END_INDEX: stageMapping.ORDER_TRACKED_PRIMARY_END_INDEX,
  ORDER_MANUFACTURING_REQUIRED_COLUMN_KEYS: stageMapping.ORDER_MANUFACTURING_REQUIRED_COLUMN_KEYS,
  ORDER_PROGRESS_STAGE_WEIGHTS: stageProgress.ORDER_PROGRESS_STAGE_WEIGHTS,
  LEGACY_ORDER_COLUMN_KEY_MAP: stageMapping.LEGACY_ORDER_COLUMN_KEY_MAP,
  normalizeOrderColumnKey: stageMapping.normalizeOrderColumnKey,
  getTrackedSecondaryHeaderCells: stageMapping.getTrackedSecondaryHeaderCells,
  getSecondaryHeaderForPrimaryColumn: stageMapping.getSecondaryHeaderForPrimaryColumn,
  isPrimaryCellHighlighted: stageHighlighting.isPrimaryCellHighlighted,
  hasValidMark: stageHighlighting.hasValidMark,
  isCleared: stageHighlighting.isCleared,
  getTrackedStageLabel: stageProgress.getTrackedStageLabel,
  getTrackedStageWeight: stageProgress.getTrackedStageWeight,
  getItemActiveRoleStage: stageProgress.getItemActiveRoleStage,
  getItemActiveStage: stageProgress.getItemActiveStage,
  getItemAssignedStage: stageProgress.getItemAssignedStage,
  getItemEffectiveColumnTimestamp: stageProgress.getItemEffectiveColumnTimestamp,
  getItemManufacturingMeta: stageProgress.getItemManufacturingMeta,
  getLatestTimestamp: stageProgress.getLatestTimestamp,
  getEarliestTimestamp: stageProgress.getEarliestTimestamp,
  formatDateLabel: stageFormatters.formatDateLabel,
  truncateTelegramLabel: stageFormatters.truncateTelegramLabel,
  normalizeTelegramButtonText: stageFormatters.normalizeTelegramButtonText,
  buildTelegramProgressBar: stageFormatters.buildTelegramProgressBar,
  getStageStatusMarker: stageFormatters.getStageStatusMarker,
  shortFullName: stageFormatters.shortFullName,
  getReadableOrderStatus: stageFormatters.getReadableOrderStatus,
  getStatusEmoji: stageFormatters.getStatusEmoji,
  getReadableItemStatus: stageFormatters.getReadableItemStatus,
  getOrderItemCount: stageFormatters.getOrderItemCount,
  getItemCurrentStageLabel: stageFormatters.getItemCurrentStageLabel,
  getOrderItemDisplayName: stageFormatters.getOrderItemDisplayName,
  getOrderDisplayName: stageFormatters.getOrderDisplayName,
  getCustomerDisplayName: stageFormatters.getCustomerDisplayName,
  buildCustomerSharePayload: accessShareHelpers.buildCustomerSharePayload,
  getCustomerKeyboardReplyMarkup: accessShareHelpers.getCustomerKeyboardReplyMarkup,
  getCustomerRemoveKeyboardReplyMarkup: accessShareHelpers.getCustomerRemoveKeyboardReplyMarkup,
  getCustomerAccessClosedText: accessShareHelpers.getCustomerAccessClosedText,
  getCustomerFullOrderText: cardRenderers.getCustomerFullOrderText,
  getCustomerBackToItemsButtonText: cardRenderers.getCustomerBackToItemsButtonText,
  getCustomerOrderCardMessage: cardRenderers.getCustomerOrderCardMessage,
  getCustomerItemCardMessage: cardRenderers.getCustomerItemCardMessage,
  getCustomerOrderChangedItemsText: accessShareHelpers.getCustomerOrderChangedItemsText,
  getCustomerOrderUpdateItemText: accessShareHelpers.getCustomerOrderUpdateItemText,
  CUSTOMER_FULL_ORDER_BUTTON_TEXT: cardRenderers.CUSTOMER_FULL_ORDER_BUTTON_TEXT,
  CUSTOMER_CALLBACK_ACTION_ITEM: cardRenderers.CUSTOMER_CALLBACK_ACTION_ITEM,
  CUSTOMER_CALLBACK_ACTION_ORDER: cardRenderers.CUSTOMER_CALLBACK_ACTION_ORDER,
  ensureCustomerOrderAccess: accessShareHelpers.ensureCustomerOrderAccess,
  CUSTOMER_START_PREFIX: cardRenderers.CUSTOMER_START_PREFIX,
  extractCustomerAccessTokenFromStartText: accessShareHelpers.extractCustomerAccessTokenFromStartText,
  parseCustomerCallbackData: accessShareHelpers.parseCustomerCallbackData,
  resolveCustomerBackToItemsFromText: accessShareHelpers.resolveCustomerBackToItemsFromText,
  resolveCustomerItemSelectionFromText: accessShareHelpers.resolveCustomerItemSelectionFromText,
  resolveRememberedCustomerAccess: accessShareHelpers.resolveRememberedCustomerAccess,
  getCustomerAlreadyLinkedText: accessShareHelpers.getCustomerAlreadyLinkedText,
  getCustomerSubscriptionReadyText: accessShareHelpers.getCustomerSubscriptionReadyText,
  getCustomerOrderShare: accessShareHelpers.getCustomerOrderShare,
  issueCustomerOrderAccess: accessShareHelpers.issueCustomerOrderAccess,
  notifyCustomerOrderArchived: telegramSender.notifyCustomerOrderArchived,
  notifyCustomerOrderCreated: telegramSender.notifyCustomerOrderCreated,
  notifyCustomerOrderRestored: telegramSender.notifyCustomerOrderRestored,
  notifyCustomerOrderStatusText: telegramSender.notifyCustomerOrderStatusText,
  sendCustomerTelegramMessage: telegramSender.sendCustomerTelegramMessage,
  _internal: {
    stageMapping,
    stageHighlighting,
    stageProgress,
    stageFormatters,
    cardRenderers,
    accessShareHelpers,
    telegramSender,
  },
};

module.exports = publicExports;
